#!/usr/bin/env bash
# Usage: ranchervm export CONFIG [--include-keys]
# Summary: Export a configuration, ignoring key files (unless specified)
# Help: This command will export a configuration to a file so it can be imported on another machine.

set -e

__ranchervm_config $1

if [ -z "$config" ]; then
  echo "No name provided"
  exit 1
fi

if [ ! -d $_RANCHERVM_ROOT/$config_path ]; then
  echo "No configuration named $1 found."
  ranchervm list
  exit 1
fi

if [ "$2" = "--include-keys" ]; then
  include_keys=1
fi

echo "Exporting: $config"

pushd $_RANCHERVM_ROOT/$config_path > /dev/null
export_file="$_RANCHERVM_ROOT/exports/${config}.tar.gz"
rm -f $export_file

if [ "$include_keys" = "1" ]; then
  tar czf $export_file ./
else
  tar czf $export_file --exclude '*.pem' ./
fi

popd > /dev/null
