#!/usr/bin/env bash
# Usage: ranchervm update
# Summary: This will update ranchervm to the latest using git
# Help: This command makes it easy to update ranchervm to the latest version from trobrock/ranchervm@master

set -e

__ranchervm_config $1

cd $_RANCHERVM_ROOT
git fetch --tags origin
tag="$( git describe --tags --abbrev=0 `git rev-list --tags --max-count=1` )"
diff="$( git cherry -v HEAD $tag | wc -l )"

if [ "$diff" -eq 0 ]; then
  echo "Already up to date."
else
  git reset --hard $tag
  echo "Updated to $tag!"
fi
